
CREATE SCHEMA `<YOUR SCHEMA NAME HERE>` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `<YOUR SCHEMA NAME HERE>`.`TOPICS` (
  `idtopic` INT NOT NULL,
  `topicName` VARCHAR(45) NULL,
  `topicContent` TEXT NULL,
  PRIMARY KEY (`idtopic`));
  
  
  GRANT ALL PRIVILEGES ON `<YOUR SCHEMA NAME HERE>`.* TO '<YOUR USERNAME>'@'localhost' IDENTIFIED BY '<YOUR PASSWORD>';